//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pedidos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fabrica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fabrica()
        {
            this.ArticulosEnFabricas = new HashSet<ArticulosEnFabrica>();
            this.DetallesDePedidos = new HashSet<DetallesDePedido>();
        }
    
        public int id_fabrica { get; set; }
        public string nombre_fabrica { get; set; }
        public string numero_telefono { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticulosEnFabrica> ArticulosEnFabricas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesDePedido> DetallesDePedidos { get; set; }
    }
}
