//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pedidos.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbpedidosEntities : DbContext
    {
        public dbpedidosEntities()
            : base("name=dbpedidosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Articulo> Articulos { get; set; }
        public virtual DbSet<ArticulosEnFabrica> ArticulosEnFabricas { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<DetallesDePedido> DetallesDePedidos { get; set; }
        public virtual DbSet<DireccionesCliente> DireccionesClientes { get; set; }
        public virtual DbSet<Fabrica> Fabricas { get; set; }
        public virtual DbSet<Pedido> Pedidos { get; set; }
    }
}
